name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run:
        description: "Build Test"
        required: true
        default: "true"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: 精简系统释放磁盘空间 (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: |
          docker build -t build-openwrt-env .
          docker run -i -v $(pwd)/openwrt:/openwrt \
          -e openwrt_upstream="https://github.com/coolsnowwolf/lede" \
          build-openwrt-env

      - name: LS
        run: |
          ls -l
          df -h /
