name: Docker Build

on:
  # push:
  #  branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run:
        description: "Build Test"
        required: true
        default: "true"    

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: 增加空间
        run: |
          sudo -E apt update
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt -y purge azure-cli* ghc* zulu* llvm*  firefox google* dotnet* powershell* openjdk* mysql* php*   mongodb* dotnet* moby* snap*

          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          
          docker rmi `docker images -q`
          sudo -E swapoff -a
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: |
          docker build -t openwrt .        
          docker run --rm -i -v $(pwd):/output \
          -e openwrt_upstream="https://github.com/coolsnowwolf/lede" \
          openwrt

      - name: LS
        run: |
          ls -l
