name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      run:
        description: "Build Test"
        required: true
        default: "true"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: 精简系统释放磁盘空间 (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: |
          sudo docker build -t build-openwrt-env . && 
          
          sudo docker run -i \ 
          -v $(pwd)/openwrt:/home/builder/openwrt \
          -v $(pwd)/.config:/home/builder/.config \
          -e openwrt_upstream=https://github.com/openwrt/openwrt \
          -e openwrt_upstream_branch=openwrt-23.05 \
          build-openwrt-env

      - name: LS
        run: |
          ls -l
          df -h /
