name: Build Docker Image

on:
  release:
    types: [published]
  #   paths:
  #     - "configs/**"
  #     - ".github/workflows/build-openwrt.yml"
  #     - "scripts/openwrt/**"
  #   branches-ignore:
  #     - stable
  # schedule:
  #   - cron: "0 19 * * *"
  workflow_dispatch:
    inputs:
      run:
        description: "Build & Push"
        required: true
        default: "true"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: shashiikora/build-openwrt-env
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          tags: "latest,${{ matrix.platform }}"
          platforms: linux/amd64,linux/arm64
