name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: |
          docker build -t openwrt .        
          docker run --rm -i -v $(pwd):/bin-output \
          -e openwrt_upstream="https://github.com/coolsnowwolf/lede" \
          openwrt
